name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Installer pnpm
      - run: corepack enable
      - run: pnpm install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v4

      # Nx Affected avec pnpm
      - run: pnpm nx affected -t lint test build --skip-nx-cache
